/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import java.awt.Color;


/**
 *
 * @author noe
 */
public class RegistroProductos extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpciones
     */
    public RegistroProductos() {
        initComponents();
        // Aplicar el efecto de borde negro al pasar el cursor
        ButtonHoverEffect.applyBorderOnHoverEffect(agregar_prod);
        ButtonHoverEffect.applyBorderOnHoverEffect(modificar_prod);
        ButtonHoverEffect.applyBorderOnHoverEffect(eliminar_prod);
        ButtonHoverEffect.applyBorderOnHoverEffect(buscar_prod);
        ButtonHoverEffect.applyBorderOnHoverEffect(salir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        funciones = new javax.swing.JToolBar();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        agregar_prod = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        modificar_prod = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        eliminar_prod = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        buscar_prod = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 800));

        funciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        funciones.setFloatable(false);
        funciones.setRollover(true);

        jSeparator1.setEnabled(false);
        jSeparator1.setRequestFocusEnabled(false);
        jSeparator1.setSeparatorSize(new java.awt.Dimension(120, 10));
        funciones.add(jSeparator1);

        agregar_prod.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        agregar_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_item.png"))); // NOI18N
        agregar_prod.setText("Agregar producto");
        agregar_prod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        agregar_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar_prod.setFocusable(false);
        agregar_prod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregar_prod.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_prodActionPerformed(evt);
            }
        });
        funciones.add(agregar_prod);

        jSeparator2.setSeparatorSize(new java.awt.Dimension(25, 10));
        funciones.add(jSeparator2);

        modificar_prod.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        modificar_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modify.png"))); // NOI18N
        modificar_prod.setText("Modificar producto");
        modificar_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar_prod.setFocusable(false);
        modificar_prod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificar_prod.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_prodActionPerformed(evt);
            }
        });
        funciones.add(modificar_prod);

        jSeparator3.setSeparatorSize(new java.awt.Dimension(25, 10));
        funciones.add(jSeparator3);

        eliminar_prod.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        eliminar_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        eliminar_prod.setText("Eliminar producto");
        eliminar_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar_prod.setFocusable(false);
        eliminar_prod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminar_prod.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_prodActionPerformed(evt);
            }
        });
        funciones.add(eliminar_prod);

        jSeparator4.setSeparatorSize(new java.awt.Dimension(25, 10));
        funciones.add(jSeparator4);

        buscar_prod.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        buscar_prod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        buscar_prod.setText("Buscar producto");
        buscar_prod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar_prod.setFocusable(false);
        buscar_prod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscar_prod.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscar_prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_prodActionPerformed(evt);
            }
        });
        funciones.add(buscar_prod);

        jSeparator5.setSeparatorSize(new java.awt.Dimension(25, 10));
        funciones.add(jSeparator5);

        salir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        salir.setText("Regresar al menú");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setFocusable(false);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        funciones.add(salir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(funciones, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(funciones, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 692, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar_prodActionPerformed

    private void agregar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_prodActionPerformed

    private void eliminar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_prodActionPerformed

    private void modificar_prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_prodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_prodActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed

             // Cierra el frame actual
            this.dispose(); 

            // Abre el nuevo frame
            MenuOpciones opciones = new MenuOpciones(); // Reemplaza con el nombre de tu clase para el nuevo frame
            opciones.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar_prod;
    private javax.swing.JButton buscar_prod;
    private javax.swing.JButton eliminar_prod;
    private javax.swing.JToolBar funciones;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JButton modificar_prod;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
