/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

// importar librerías de swing
import java.awt.Color;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

// Importar las clases de lógica:
import com.mycompany.proyecto1.Archivo;
import com.mycompany.proyecto1.Utilidades;
import com.mycompany.proyecto1.Validador;

// Importar las clases de objetos:
import com.mycompany.proyecto1.Producto;
import com.mycompany.proyecto1.TipoProducto;

/**
 *
 * @author noe
 */
public class VentanaModificar extends javax.swing.JFrame {
    
    // Constructor vacío para que VentanaModificar pueda recibir parámetros sin conflictos en el main
    public VentanaModificar(){
        initComponents();
    }
    /**
     * Creates new form VentanaModificar
     * @param producto
     */
    public VentanaModificar(Producto producto) {
        initComponents();
        
        // Evitar que la ventana emergente VentanaModificar cierre el programa
        setDefaultCloseOperation(VentanaModificar.DISPOSE_ON_CLOSE);
        
        // Cargar los datos del producto en los espacios correspondientes
        cargarDatosProducto(producto);
        
         // Define los colores
         Color hoverColor = new Color(150,150,150); // Gris claro (al pasar el cursor)
         Color originalColor = Color.BLACK; // Negro (borde inicial)

         // Crear la instancia de ButtonHoverEffect para el efecto
         ButtonHoverEffect hoverEffect = new ButtonHoverEffect(hoverColor, originalColor);
        
         hoverEffect.applyTo(guardar_cambios);
         hoverEffect.applyTo(eliminar_producto);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesProducto = new javax.swing.JPanel();
        codigo_art = new javax.swing.JLabel();
        box_codigo_art = new javax.swing.JTextField();
        codigo_prod = new javax.swing.JLabel();
        box_codigo_prod = new javax.swing.JComboBox<>();
        tipo_art = new javax.swing.JLabel();
        combo_tipo_art = new javax.swing.JComboBox<>();
        tammanio_bici1 = new javax.swing.JLabel();
        combo_tammanio_bici = new javax.swing.JComboBox<>();
        nombre_art = new javax.swing.JLabel();
        box_nombre_art = new javax.swing.JTextField();
        marca_art = new javax.swing.JLabel();
        box_marca_art = new javax.swing.JTextField();
        guardar_cambios = new javax.swing.JButton();
        marca_art1 = new javax.swing.JLabel();
        box_marca_art1 = new javax.swing.JTextField();
        marca_art2 = new javax.swing.JLabel();
        box_marca_art2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        eliminar_producto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        codigo_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        codigo_art.setText("Código artículo");

        box_codigo_art.setBackground(new java.awt.Color(255, 255, 255));
        box_codigo_art.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        box_codigo_art.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        box_codigo_art.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_codigo_art.setEnabled(false);
        box_codigo_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_codigo_artActionPerformed(evt);
            }
        });

        codigo_prod.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        codigo_prod.setText("Código producto");

        box_codigo_prod.setBackground(new java.awt.Color(255, 255, 255));
        box_codigo_prod.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        box_codigo_prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo prod" }));
        box_codigo_prod.setBorder(null);
        box_codigo_prod.setFocusable(false);
        box_codigo_prod.setRequestFocusEnabled(false);

        tipo_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        tipo_art.setText("Tipo de artículo");

        combo_tipo_art.setBackground(new java.awt.Color(255, 255, 255));
        combo_tipo_art.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        combo_tipo_art.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicicleta", "Accesorio", "Suplemento" }));
        combo_tipo_art.setBorder(null);
        combo_tipo_art.setFocusable(false);
        combo_tipo_art.setRequestFocusEnabled(false);
        combo_tipo_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipo_artActionPerformed(evt);
            }
        });

        tammanio_bici1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        tammanio_bici1.setText("Tamaño (bici)");

        combo_tammanio_bici.setBackground(new java.awt.Color(255, 255, 255));
        combo_tammanio_bici.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        combo_tammanio_bici.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "16", "22", "26", "27", "27.5", "29" }));
        combo_tammanio_bici.setBorder(null);
        combo_tammanio_bici.setFocusable(false);
        combo_tammanio_bici.setRequestFocusEnabled(false);
        combo_tammanio_bici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tammanio_biciActionPerformed(evt);
            }
        });

        nombre_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        nombre_art.setText("Nombre");

        box_nombre_art.setBackground(new java.awt.Color(255, 255, 255));
        box_nombre_art.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_nombre_art.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_nombre_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_nombre_artActionPerformed(evt);
            }
        });

        marca_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        marca_art.setText("Marca");

        box_marca_art.setBackground(new java.awt.Color(255, 255, 255));
        box_marca_art.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_marca_art.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_marca_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_marca_artActionPerformed(evt);
            }
        });

        guardar_cambios.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        guardar_cambios.setText("GUARDAR");
        guardar_cambios.setBorder(null);
        guardar_cambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_cambiosActionPerformed(evt);
            }
        });

        marca_art1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        marca_art1.setText("Precio");

        box_marca_art1.setBackground(new java.awt.Color(255, 255, 255));
        box_marca_art1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_marca_art1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_marca_art1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_marca_art1ActionPerformed(evt);
            }
        });

        marca_art2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        marca_art2.setText("Cantidad");

        box_marca_art2.setBackground(new java.awt.Color(255, 255, 255));
        box_marca_art2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_marca_art2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_marca_art2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_marca_art2ActionPerformed(evt);
            }
        });

        eliminar_producto.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        eliminar_producto.setForeground(new java.awt.Color(204, 0, 0));
        eliminar_producto.setText("ELIMINAR");
        eliminar_producto.setBorder(null);
        eliminar_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_productoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesProductoLayout = new javax.swing.GroupLayout(opcionesProducto);
        opcionesProducto.setLayout(opcionesProductoLayout);
        opcionesProductoLayout.setHorizontalGroup(
            opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesProductoLayout.createSequentialGroup()
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addGroup(opcionesProductoLayout.createSequentialGroup()
                                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(box_nombre_art, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(opcionesProductoLayout.createSequentialGroup()
                                            .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(codigo_prod)
                                                .addComponent(codigo_art)
                                                .addComponent(tammanio_bici1))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(combo_tammanio_bici, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(box_codigo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(combo_tipo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(box_codigo_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(opcionesProductoLayout.createSequentialGroup()
                                            .addComponent(marca_art)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(box_marca_art, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tipo_art)
                                    .addComponent(nombre_art)
                                    .addComponent(marca_art1)
                                    .addGroup(opcionesProductoLayout.createSequentialGroup()
                                        .addComponent(marca_art2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(box_marca_art2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(box_marca_art1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 43, Short.MAX_VALUE))))
                    .addGroup(opcionesProductoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator7))
                    .addGroup(opcionesProductoLayout.createSequentialGroup()
                        .addComponent(guardar_cambios, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        opcionesProductoLayout.setVerticalGroup(
            opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_codigo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_codigo_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_tipo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tammanio_bici1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_tammanio_bici, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_nombre_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_marca_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_art1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_marca_art1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_art2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_marca_art2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eliminar_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(guardar_cambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(opcionesProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(46, 46, 46)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(opcionesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(10, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_codigo_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_codigo_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_codigo_artActionPerformed

    private void combo_tipo_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipo_artActionPerformed

        String tipoSeleccionado = (String) combo_tipo_art.getSelectedItem();

        // Activar o desactivar el combo de tamaño de bicicleta
        if ("Bicicleta".equals(tipoSeleccionado)) {
            combo_tammanio_bici.setEnabled(true);
        } else {
            combo_tammanio_bici.setEnabled(false);
            combo_tammanio_bici.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_combo_tipo_artActionPerformed

    private void combo_tammanio_biciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tammanio_biciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tammanio_biciActionPerformed

    private void box_nombre_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_nombre_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_nombre_artActionPerformed

    private void box_marca_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_marca_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_marca_artActionPerformed

    private void guardar_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_cambiosActionPerformed
        String ruta = "productos.json";
        Archivo archivo = new Archivo();

        try {
            Producto[] productos = (Producto[]) archivo.leerArchivo(ruta, Producto[].class);
            if (productos == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay productos registrados.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            int codigoArticulo = Integer.parseInt(box_codigo_art.getText());
            for (Producto producto : productos) {
                if (producto.getCodigoArticulo() == codigoArticulo) {
                    // Obtener y validar los datos del formulario
                    String codigoProductoTexto = (String) box_codigo_prod.getSelectedItem();
                    int codigoProducto = Integer.parseInt(codigoProductoTexto.split(" - ")[0]);
                    String tipoArticulo = combo_tipo_art.getSelectedItem().toString();
                    String tamanoBici = "Bicicleta".equals(tipoArticulo) ? combo_tammanio_bici.getSelectedItem().toString() : null;
                    String nombre = box_nombre_art.getText().trim();
                    String marca = box_marca_art.getText().trim();
                    String precioTexto = box_marca_art1.getText().trim();
                    String cantidadTexto = box_marca_art2.getText().trim();

                    // Validaciones
                    if (!Validador.validarAlfabetico(nombre)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    if (!Validador.validarAlfabetico(marca)) {
                        javax.swing.JOptionPane.showMessageDialog(this, "La marca solo puede contener letras.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    if (!Validador.validarNumerico(precioTexto) || Integer.parseInt(precioTexto) <= 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "El precio debe ser un número mayor a 0.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    if (!Validador.validarNumerico(cantidadTexto) || Integer.parseInt(cantidadTexto) < 0) {
                        javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser un número no negativo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                        return;
                    }

                    // Actualizar los valores del producto
                    producto.setCodigoProducto(codigoProducto);
                    producto.setTipoArticulo(tipoArticulo);
                    producto.setTamanoBici(tamanoBici);
                    producto.setNombre(nombre);
                    producto.setMarca(marca);
                    producto.setPrecio(Integer.parseInt(precioTexto));
                    producto.setCantidad(Integer.parseInt(cantidadTexto));
                    break;
                }
            }

            // Guardar los cambios en el archivo
            archivo.guardarArchivo(ruta, productos);

            javax.swing.JOptionPane.showMessageDialog(this, "Producto modificado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar los cambios: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardar_cambiosActionPerformed

    private void box_marca_art1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_marca_art1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_marca_art1ActionPerformed

    private void box_marca_art2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_marca_art2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_marca_art2ActionPerformed

    private void eliminar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_productoActionPerformed
        String ruta = "productos.json";
        Archivo archivo = new Archivo();

        try {
            Producto[] productos = (Producto[]) archivo.leerArchivo(ruta, Producto[].class);
            if (productos == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay productos registrados.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            int codigoArticulo = Integer.parseInt(box_codigo_art.getText());

            // Validar si el producto ya ha sido facturado
            if (Validador.productoHaSidoFacturado(codigoArticulo)) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Este producto ya ha sido facturado y no puede eliminarse.", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Confirmación antes de eliminar
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar este producto?", 
                "Confirmación de eliminación", 
                javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm != javax.swing.JOptionPane.YES_OPTION) {
                return;
            }

            // Filtrar el producto a eliminar
            Producto[] productosActualizados = Arrays.stream(productos)
                .filter(producto -> producto.getCodigoArticulo() != codigoArticulo)
                .toArray(Producto[]::new);

            // Guardar los productos actualizados
            archivo.guardarArchivo(ruta, productosActualizados);

            javax.swing.JOptionPane.showMessageDialog(this, "Producto eliminado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el producto: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_eliminar_productoActionPerformed

    private void cargarDatosProducto(Producto producto) {
        box_codigo_art.setText(String.valueOf(producto.getCodigoArticulo()));

        // Cargar los tipos de producto en el comboBox
        Utilidades.cargarTiposDeProducto("tiposProductos.json", box_codigo_prod);

        // Seleccionar el tipo de producto correspondiente
        for (int i = 0; i < box_codigo_prod.getItemCount(); i++) {
            String item = (String) box_codigo_prod.getItemAt(i);
            int codigo = Integer.parseInt(item.split(" - ")[0]);
            if (codigo == producto.getCodigoProducto()) {
                box_codigo_prod.setSelectedIndex(i);
                break;
            }
        }

        // Configurar otros valores
        combo_tipo_art.setSelectedItem(producto.getTipoArticulo());
        combo_tammanio_bici.setSelectedItem(producto.getTamanoBici());
        box_nombre_art.setText(producto.getNombre());
        box_marca_art.setText(producto.getMarca());
        box_marca_art1.setText(String.valueOf(producto.getPrecio()));
        box_marca_art2.setText(String.valueOf(producto.getCantidad()));
    }

    //Clase para obtener los datos de un tipo de producto
    public static String obtenerNombreTipoProducto(int codigoProducto) {
        String ruta = "tiposProductos.json";
        Archivo archivo = new Archivo();

        try {
            // Leer los tipos de productos desde el archivo JSON
            TipoProducto[] tipos = (TipoProducto[]) archivo.leerArchivo(ruta, TipoProducto[].class);

            if (tipos != null) {
                // Buscar el nombre del tipo de producto correspondiente al código
                for (TipoProducto tipo : tipos) {
                    if (tipo.getCodigo() == codigoProducto) {
                        return tipo.getNombre();
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Error al obtener el nombre del tipo de producto: " + e.getMessage());
        }

        // Retornar "Desconocido" si no se encuentra el código
        return "Desconocido";
    }


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_codigo_art;
    private javax.swing.JComboBox<String> box_codigo_prod;
    private javax.swing.JTextField box_marca_art;
    private javax.swing.JTextField box_marca_art1;
    private javax.swing.JTextField box_marca_art2;
    private javax.swing.JTextField box_nombre_art;
    private javax.swing.JLabel codigo_art;
    private javax.swing.JLabel codigo_prod;
    private javax.swing.JComboBox<String> combo_tammanio_bici;
    private javax.swing.JComboBox<String> combo_tipo_art;
    private javax.swing.JButton eliminar_producto;
    private javax.swing.JButton guardar_cambios;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel marca_art;
    private javax.swing.JLabel marca_art1;
    private javax.swing.JLabel marca_art2;
    private javax.swing.JLabel nombre_art;
    private javax.swing.JPanel opcionesProducto;
    private javax.swing.JLabel tammanio_bici1;
    private javax.swing.JLabel tipo_art;
    // End of variables declaration//GEN-END:variables
}
