/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

// importar librerías de swing
import java.awt.Color;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

// Importar las clases de lógica:
import com.mycompany.proyecto1.Archivo;
import com.mycompany.proyecto1.Validador;
import com.mycompany.proyecto1.Utilidades;

// Importar las clases de objetos:
import com.mycompany.proyecto1.TipoProducto;
import com.mycompany.proyecto1.Producto;

/**
 *
 * @author noe
 */
public class VentanaModificar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar() {
        initComponents();
            // Define los colores
            Color hoverColor = new Color(150,150,150); // Gris claro (al pasar el cursor)
            Color originalColor = Color.BLACK; // Negro (borde inicial)

            // Crear la instancia de ButtonHoverEffect para el efecto
            ButtonHoverEffect hoverEffect = new ButtonHoverEffect(hoverColor, originalColor);
        
            hoverEffect.applyTo(guardar_cambios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesProducto = new javax.swing.JPanel();
        codigo_art = new javax.swing.JLabel();
        box_codigo_art = new javax.swing.JTextField();
        codigo_prod = new javax.swing.JLabel();
        box_codigo_prod = new javax.swing.JComboBox<>();
        tipo_art = new javax.swing.JLabel();
        combo_tipo_art = new javax.swing.JComboBox<>();
        tammanio_bici1 = new javax.swing.JLabel();
        combo_tammanio_bici = new javax.swing.JComboBox<>();
        nombre_art = new javax.swing.JLabel();
        box_nombre_art = new javax.swing.JTextField();
        marca_art = new javax.swing.JLabel();
        box_marca_art = new javax.swing.JTextField();
        guardar_cambios = new javax.swing.JButton();
        marca_art1 = new javax.swing.JLabel();
        box_marca_art1 = new javax.swing.JTextField();
        marca_art2 = new javax.swing.JLabel();
        box_marca_art2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigo_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        codigo_art.setText("Código artículo");

        box_codigo_art.setBackground(new java.awt.Color(255, 255, 255));
        box_codigo_art.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        box_codigo_art.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        box_codigo_art.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_codigo_art.setEnabled(false);
        box_codigo_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_codigo_artActionPerformed(evt);
            }
        });

        codigo_prod.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        codigo_prod.setText("Código producto");

        box_codigo_prod.setBackground(new java.awt.Color(255, 255, 255));
        box_codigo_prod.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        box_codigo_prod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo prod" }));
        box_codigo_prod.setBorder(null);
        box_codigo_prod.setFocusable(false);
        box_codigo_prod.setRequestFocusEnabled(false);

        tipo_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        tipo_art.setText("Tipo de artículo");

        combo_tipo_art.setBackground(new java.awt.Color(255, 255, 255));
        combo_tipo_art.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        combo_tipo_art.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicicleta", "Accesorio", "Suplemento" }));
        combo_tipo_art.setBorder(null);
        combo_tipo_art.setFocusable(false);
        combo_tipo_art.setRequestFocusEnabled(false);
        combo_tipo_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tipo_artActionPerformed(evt);
            }
        });

        tammanio_bici1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        tammanio_bici1.setText("Tamaño (bici)");

        combo_tammanio_bici.setBackground(new java.awt.Color(255, 255, 255));
        combo_tammanio_bici.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        combo_tammanio_bici.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "16", "22", "26", "27", "27.5", "29" }));
        combo_tammanio_bici.setBorder(null);
        combo_tammanio_bici.setFocusable(false);
        combo_tammanio_bici.setRequestFocusEnabled(false);
        combo_tammanio_bici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_tammanio_biciActionPerformed(evt);
            }
        });

        nombre_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        nombre_art.setText("Nombre");

        box_nombre_art.setBackground(new java.awt.Color(255, 255, 255));
        box_nombre_art.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_nombre_art.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_nombre_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_nombre_artActionPerformed(evt);
            }
        });

        marca_art.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        marca_art.setText("Marca");

        box_marca_art.setBackground(new java.awt.Color(255, 255, 255));
        box_marca_art.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_marca_art.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_marca_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_marca_artActionPerformed(evt);
            }
        });

        guardar_cambios.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        guardar_cambios.setText("G U A R D A R");
        guardar_cambios.setBorder(null);
        guardar_cambios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar_cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_cambiosActionPerformed(evt);
            }
        });

        marca_art1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        marca_art1.setText("Precio");

        box_marca_art1.setBackground(new java.awt.Color(255, 255, 255));
        box_marca_art1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_marca_art1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_marca_art1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_marca_art1ActionPerformed(evt);
            }
        });

        marca_art2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        marca_art2.setText("Cantidad");

        box_marca_art2.setBackground(new java.awt.Color(255, 255, 255));
        box_marca_art2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_marca_art2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_marca_art2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_marca_art2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesProductoLayout = new javax.swing.GroupLayout(opcionesProducto);
        opcionesProducto.setLayout(opcionesProductoLayout);
        opcionesProductoLayout.setHorizontalGroup(
            opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesProductoLayout.createSequentialGroup()
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addGroup(opcionesProductoLayout.createSequentialGroup()
                                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(box_nombre_art, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(opcionesProductoLayout.createSequentialGroup()
                                            .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(codigo_prod)
                                                .addComponent(codigo_art)
                                                .addComponent(tammanio_bici1))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(combo_tammanio_bici, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(box_codigo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(combo_tipo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(box_codigo_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(opcionesProductoLayout.createSequentialGroup()
                                            .addComponent(marca_art)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(box_marca_art, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tipo_art)
                                    .addComponent(nombre_art)
                                    .addComponent(marca_art1)
                                    .addGroup(opcionesProductoLayout.createSequentialGroup()
                                        .addComponent(marca_art2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(guardar_cambios, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(box_marca_art2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(box_marca_art1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 43, Short.MAX_VALUE))))
                    .addGroup(opcionesProductoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator7)))
                .addContainerGap())
        );
        opcionesProductoLayout.setVerticalGroup(
            opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_codigo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_codigo_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_tipo_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tammanio_bici1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_tammanio_bici, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_nombre_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_art, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_marca_art, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_art1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_marca_art1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca_art2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_marca_art2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(guardar_cambios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(opcionesProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(46, 46, 46)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(opcionesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_codigo_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_codigo_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_codigo_artActionPerformed

    private void combo_tipo_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tipo_artActionPerformed

        String tipoSeleccionado = (String) combo_tipo_art.getSelectedItem();

        // Activar o desactivar el combo de tamaño de bicicleta
        if ("Bicicleta".equals(tipoSeleccionado)) {
            combo_tammanio_bici.setEnabled(true);
        } else {
            combo_tammanio_bici.setEnabled(false);
            combo_tammanio_bici.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_combo_tipo_artActionPerformed

    private void combo_tammanio_biciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_tammanio_biciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_tammanio_biciActionPerformed

    private void box_nombre_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_nombre_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_nombre_artActionPerformed

    private void box_marca_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_marca_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_marca_artActionPerformed

    private void guardar_cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_cambiosActionPerformed
        String ruta = "productos.json";
        Archivo archivo = new Archivo();

        try {
            // Leer productos existentes del archivo JSON
            Producto[] productos = (Producto[]) archivo.leerArchivo(ruta, Producto[].class);
            if (productos == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay productos registrados.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Encontrar el producto por código
            int codigoArticulo = Integer.parseInt(box_codigo_art.getText());
            for (Producto producto : productos) {
                if (producto.getCodigoArticulo() == codigoArticulo) {
                    // Actualizar los valores del producto
                    producto.setCodigoProducto(Integer.parseInt(box_codigo_prod.getSelectedItem().toString()));
                    producto.setTipoArticulo(combo_tipo_art.getSelectedItem().toString());
                    producto.setTamanoBici("Bicicleta".equals(combo_tipo_art.getSelectedItem().toString()) 
                        ? combo_tammanio_bici.getSelectedItem().toString() 
                        : null);
                    producto.setNombre(box_nombre_art.getText().trim());
                    producto.setMarca(box_marca_art.getText().trim());
                    producto.setPrecio(Integer.parseInt(box_marca_art1.getText().trim()));
                    producto.setCantidad(Integer.parseInt(box_marca_art2.getText().trim()));
                    break;
                }
            }

            // Guardar los productos actualizados en el archivo JSON
            archivo.guardarArchivo(ruta, productos);

            javax.swing.JOptionPane.showMessageDialog(this, "Producto modificado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose(); // Cerrar la ventana actual

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar los cambios: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardar_cambiosActionPerformed

    private void box_marca_art1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_marca_art1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_marca_art1ActionPerformed

    private void box_marca_art2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_marca_art2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_marca_art2ActionPerformed

    public void cargarDatosProducto(int codigoArticulo) {
        String ruta = "productos.json";
        Archivo archivo = new Archivo();

        try {
            Producto[] productos = (Producto[]) archivo.leerArchivo(ruta, Producto[].class);

            if (productos == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "No hay productos registrados.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            for (Producto p : productos) {
                if (p.getCodigoArticulo() == codigoArticulo) {
                    // Llenar los campos con los datos del producto
                    box_codigo_art.setText(String.valueOf(p.getCodigoArticulo()));
                    box_codigo_prod.setSelectedItem(String.valueOf(p.getCodigoProducto()));
                    combo_tipo_art.setSelectedItem(p.getTipoArticulo());
                    combo_tammanio_bici.setSelectedItem(p.getTamanoBici());
                    box_nombre_art.setText(p.getNombre());
                    box_marca_art.setText(p.getMarca());
                    box_marca_art1.setText(String.valueOf(p.getPrecio()));
                    box_marca_art2.setText(String.valueOf(p.getCantidad()));
                    break;
                }
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_codigo_art;
    private javax.swing.JComboBox<String> box_codigo_prod;
    private javax.swing.JTextField box_marca_art;
    private javax.swing.JTextField box_marca_art1;
    private javax.swing.JTextField box_marca_art2;
    private javax.swing.JTextField box_nombre_art;
    private javax.swing.JLabel codigo_art;
    private javax.swing.JLabel codigo_prod;
    private javax.swing.JComboBox<String> combo_tammanio_bici;
    private javax.swing.JComboBox<String> combo_tipo_art;
    private javax.swing.JButton guardar_cambios;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel marca_art;
    private javax.swing.JLabel marca_art1;
    private javax.swing.JLabel marca_art2;
    private javax.swing.JLabel nombre_art;
    private javax.swing.JPanel opcionesProducto;
    private javax.swing.JLabel tammanio_bici1;
    private javax.swing.JLabel tipo_art;
    // End of variables declaration//GEN-END:variables
}
