/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

// importar librerías de swing
import java.awt.Color;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.table.DefaultTableModel;

// Importar las clases de lógica:
import com.mycompany.proyecto1.Archivo;
import com.mycompany.proyecto1.Facturas.Factura;
import com.mycompany.proyecto1.Facturas.UtilidadesFacturas;
import com.mycompany.proyecto1.Utilidades;
import com.mycompany.proyecto1.Validador;

// Importar las clases de objetos:
import com.mycompany.proyecto1.Producto;

/**
 *
 * @author noe
 */
public class VentanaFacturacion_prod extends javax.swing.JFrame {
    
    /**
     * Creates new form VentanaModificar
     */
    public VentanaFacturacion_prod() {
        initComponents();
            // Cargar el siguiente número de factura automáticamente
            Archivo archivo = new Archivo();
            int siguienteNumeroFactura = archivo.obtenerSiguienteCodigo("facturas.json", Factura[].class);
            box_num_fact.setText(String.valueOf(siguienteNumeroFactura));
        
            // Cargar los clientes en el comboBox de clientes al iniciar el formulario
            Utilidades.cargarClientes("registroClientes.json", combo_codigo_cliente);
        
            // Evitar que la ventana emergente VentanaModificar cierre el programa
            setDefaultCloseOperation(VentanaFacturacion_prod.DISPOSE_ON_CLOSE);
                
            // Define los colores
            Color hoverColor = new Color(150,150,150); // Gris claro (al pasar el cursor)
            Color originalColor = Color.BLACK; // Negro (borde inicial)

            // Crear la instancia de ButtonHoverEffect para el efecto
            ButtonHoverEffect hoverEffect = new ButtonHoverEffect(hoverColor, originalColor);
        
            // Configurar el campo de fecha
            Utilidades.configurarCampoFecha(formatt_fecha_recibido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_num_fact = new javax.swing.JLabel();
        box_num_fact = new javax.swing.JTextField();
        label_codigo_cliente = new javax.swing.JLabel();
        combo_codigo_cliente = new javax.swing.JComboBox<>();
        label_fecha_recibido = new javax.swing.JLabel();
        formatt_fecha_recibido = new javax.swing.JFormattedTextField();
        label_subtotal = new javax.swing.JLabel();
        box_subtotal = new javax.swing.JTextField();
        label_iva = new javax.swing.JLabel();
        box_iva = new javax.swing.JTextField();
        label_total = new javax.swing.JLabel();
        box_total = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        label_detalles = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        label_codigo_articulo = new javax.swing.JLabel();
        combo_codigo_articulo = new javax.swing.JComboBox<>();
        label_cantidad = new javax.swing.JLabel();
        box_cantidad = new javax.swing.JTextField();
        label_precio_und = new javax.swing.JLabel();
        box_precio_und = new javax.swing.JTextField();
        label_total_pagar = new javax.swing.JLabel();
        box_total_pagar = new javax.swing.JTextField();
        crear_fact = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label_num_fact.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_num_fact.setText("Num. Factura");

        box_num_fact.setBackground(new java.awt.Color(255, 255, 255));
        box_num_fact.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        box_num_fact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        box_num_fact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_num_fact.setEnabled(false);
        box_num_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_num_factActionPerformed(evt);
            }
        });

        label_codigo_cliente.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_codigo_cliente.setText("Código cliente");

        combo_codigo_cliente.setBackground(new java.awt.Color(255, 255, 255));
        combo_codigo_cliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        combo_codigo_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo prod" }));
        combo_codigo_cliente.setBorder(null);
        combo_codigo_cliente.setFocusable(false);
        combo_codigo_cliente.setRequestFocusEnabled(false);

        label_fecha_recibido.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_fecha_recibido.setText("Fecha recibido");

        formatt_fecha_recibido.setBackground(new java.awt.Color(255, 255, 255));
        formatt_fecha_recibido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formatt_fecha_recibido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        formatt_fecha_recibido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        formatt_fecha_recibido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatt_fecha_recibidoActionPerformed(evt);
            }
        });

        label_subtotal.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_subtotal.setText("Subtotal");

        box_subtotal.setBackground(new java.awt.Color(255, 255, 255));
        box_subtotal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_subtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_subtotal.setEnabled(false);
        box_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_subtotalActionPerformed(evt);
            }
        });

        label_iva.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_iva.setText("I.V.A");

        box_iva.setBackground(new java.awt.Color(255, 255, 255));
        box_iva.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_iva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_iva.setEnabled(false);
        box_iva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_ivaActionPerformed(evt);
            }
        });

        label_total.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_total.setText("TOTAL");

        box_total.setBackground(new java.awt.Color(255, 255, 255));
        box_total.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        box_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_total.setEnabled(false);
        box_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_totalActionPerformed(evt);
            }
        });

        label_detalles.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        label_detalles.setText("Detalle de la factura");

        label_codigo_articulo.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_codigo_articulo.setText("Código artículo");

        combo_codigo_articulo.setBackground(new java.awt.Color(255, 255, 255));
        combo_codigo_articulo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        combo_codigo_articulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tipo prod" }));
        combo_codigo_articulo.setBorder(null);
        combo_codigo_articulo.setFocusable(false);
        combo_codigo_articulo.setRequestFocusEnabled(false);

        label_cantidad.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_cantidad.setText("Cantidad (und)");

        box_cantidad.setBackground(new java.awt.Color(255, 255, 255));
        box_cantidad.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        box_cantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_cantidadActionPerformed(evt);
            }
        });

        label_precio_und.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_precio_und.setText("Precio (und)");

        box_precio_und.setBackground(new java.awt.Color(255, 255, 255));
        box_precio_und.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        box_precio_und.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_precio_und.setEnabled(false);
        box_precio_und.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_precio_undActionPerformed(evt);
            }
        });

        label_total_pagar.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label_total_pagar.setText("Total a pagar");

        box_total_pagar.setBackground(new java.awt.Color(255, 255, 255));
        box_total_pagar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        box_total_pagar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        box_total_pagar.setEnabled(false);
        box_total_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_total_pagarActionPerformed(evt);
            }
        });

        crear_fact.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        crear_fact.setText("CREAR FACTURA");
        crear_fact.setBorder(null);
        crear_fact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crear_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_factActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_num_fact)
                                    .addComponent(label_fecha_recibido))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(box_num_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(formatt_fecha_recibido))
                                .addGap(18, 18, 18)
                                .addComponent(label_codigo_cliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_subtotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_iva)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label_total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box_total, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_codigo_articulo)
                                    .addComponent(label_cantidad)
                                    .addComponent(label_precio_und)
                                    .addComponent(label_total_pagar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(box_total_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box_precio_und, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_codigo_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(box_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(crear_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_detalles)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_num_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_num_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_codigo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_fecha_recibido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formatt_fecha_recibido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box_subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box_iva, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_total, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box_total, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_detalles)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_codigo_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_codigo_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_precio_und, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_precio_und, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_total_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box_total_pagar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(crear_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void box_num_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_num_factActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_num_factActionPerformed

    private void box_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_totalActionPerformed

    private void box_ivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_ivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_ivaActionPerformed

    private void formatt_fecha_recibidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatt_fecha_recibidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formatt_fecha_recibidoActionPerformed

    private void box_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_subtotalActionPerformed

    private void box_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_cantidadActionPerformed

    private void box_precio_undActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_precio_undActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_precio_undActionPerformed

    private void box_total_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_total_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_total_pagarActionPerformed

    private void crear_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_factActionPerformed

    }//GEN-LAST:event_crear_factActionPerformed



    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFacturacion_prod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField box_cantidad;
    private javax.swing.JTextField box_iva;
    private javax.swing.JTextField box_num_fact;
    private javax.swing.JTextField box_precio_und;
    private javax.swing.JTextField box_subtotal;
    private javax.swing.JTextField box_total;
    private javax.swing.JTextField box_total_pagar;
    private javax.swing.JComboBox<String> combo_codigo_articulo;
    private javax.swing.JComboBox<String> combo_codigo_cliente;
    private javax.swing.JButton crear_fact;
    private javax.swing.JFormattedTextField formatt_fecha_recibido;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label_cantidad;
    private javax.swing.JLabel label_codigo_articulo;
    private javax.swing.JLabel label_codigo_cliente;
    private javax.swing.JLabel label_detalles;
    private javax.swing.JLabel label_fecha_recibido;
    private javax.swing.JLabel label_iva;
    private javax.swing.JLabel label_num_fact;
    private javax.swing.JLabel label_precio_und;
    private javax.swing.JLabel label_subtotal;
    private javax.swing.JLabel label_total;
    private javax.swing.JLabel label_total_pagar;
    // End of variables declaration//GEN-END:variables
}
